# ~/.config/starship.toml


[character]
success_symbol = '[❱](bold green)'
error_symbol = '[❱](bold red)'

[cmd_duration]
min_time = 10_000  # Show command duration over 10,000 milliseconds (=10 sec)
format = " took [$duration]($style)"

[directory]
truncation_length = 4
format = "[$path]($style)[$lock_symbol]($lock_style) "

[git_branch]
format = " [$symbol$branch]($style) "
symbol = "  "
style = "bold yellow"

[git_commit]
commit_hash_length = 8
style = "bold white"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[git_status]
conflicted = "󰞇 "
diverged = "󱡷 ${ahead_count} 󱡷  ${behind_count} "
untracked = "󰈉 ${count} "
modified = "󰷨 ${count} "
renamed = "󰾹 ${count} "
deleted = "󰩺 ${count} "
style = "bright-white"
format = "$all_status$ahead_behind"

[hostname]
ssh_only = false
format = "<[$hostname]($style)>"
trim_at = "-"
style = "bold dimmed white"
disabled = true

[julia]
format = "[$symbol$version]($style) "
symbol = "ஃ "
style = "bold green"

[memory_usage]
format = "$symbol[${ram}( | ${swap})]($style) "
threshold = 70
style = "bold dimmed white"
disabled = false


[time]
time_format = "%T"
format = "󰔛  $time($style) "
style = "bright-white"
disabled = false

[username]
style_user = "bold dimmed blue"
show_always = false

[python]
symbol = " "
style = "dimmed green"

[c]
symbol = " "
style = "dimmed gray"


[lua]
symbol=" "
style = "dimmed blue"

[rust]
symbol = "rust "
style = "dimmed orange"

[golang]
symbol = "󰟓  "
style = "dimmed blue"

[nodejs]
format = " [󰌞  $version](dimmed yellow) "

[java]
symbol = " "
style = "dimmed red"
